name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    name: Typecheck, Lint, Test, Build and E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@10.33.2 --activate

      - name: Check pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm --filter web exec playwright install --with-deps chromium

      - name: Type check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Unit test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: E2E test
        run: pnpm e2e